In [2]:
import numpy as np

In [3]:
#Q1
matrix = np.array([[1,3,2], [4,1,3],[2,5,2]])
determinant = np.linalg.det(matrix)
print(determinant)

16.999999999999993


In [5]:
#Q2
matrix_a=np.array([[4,2,3],[-1,1,-3],[2,4,9]])
eigenvalues, eigenvectors = np.linalg.eig(matrix_a)
print(eigenvalues, eigenvectors)

[8. 3. 3.] [[-0.40824829  0.87287156 -0.22952641]
 [ 0.40824829  0.21821789  0.84341429]
 [-0.81649658 -0.43643578 -0.48576739]]


In [7]:
#Q3
matrix_b=np.array([[2,2,0],[0,0,1],[4,2,0]])
inverse_b = np.linalg.inv(matrix_b)
print(inverse_b)

[[-0.5  0.   0.5]
 [ 1.   0.  -0.5]
 [ 0.   1.   0. ]]


In [8]:
#Q4
print(np.dot(matrix_b,inverse_b))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#Q5
p1=np.dot(matrix_a,matrix_b)
p2=np.dot(matrix_a,matrix_a)*2
p3= matrix_b*3
print(p1+p2-p3)

[[ 54  52  68]
 [-36 -34 -68]
 [ 72 104 154]]


In [17]:
#Q6
eigenvalues, eigenvectors = np.linalg.eig(matrix_a)
D = np.diag(eigenvalues)
Q = eigenvectors
Q_inv = np.linalg.inv(Q)

print("Matrix Q:")
print(Q)
print("Matrix D:")
print(D)

Matrix Q:
[[-0.40824829  0.87287156 -0.22952641]
 [ 0.40824829  0.21821789  0.84341429]
 [-0.81649658 -0.43643578 -0.48576739]]
Matrix D:
[[8. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]


In [18]:
#Q7
A = np.array([[2, -4, 9], [4, -3, 8], [-2, 4, -2]])
b = np.array([-38, -26, 17])
solution = np.linalg.solve(A, b)
print(solution)

[ 2.5  4.  -3. ]


In [23]:
#Q8
C= np.array([[0,1],[2,3],[4,5]])
D= np.array([[0,1, 2, 3],[4, 5, 6, 7]])
print(C.shape,D.shape)
print(C.T,D.T)

(3, 2) (2, 4)
[[0 2 4]
 [1 3 5]] [[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [24]:
#Q9
#Calculate (cd)^T
cd_transpose = np.dot(C, D).T

# Calculate d^T * c^T
d_transpose = D.T
c_transpose = C.T
d_c_transpose = np.dot(d_transpose, c_transpose)

# Check if (cd)^T = d^T * c^T
is_equal = np.array_equal(cd_transpose, d_c_transpose)

print("(cd)^T:")
print(cd_transpose)
print("d^T * c^T:")
print(d_c_transpose)
print("Are they equal?", is_equal)


(cd)^T:
[[ 4 12 20]
 [ 5 17 29]
 [ 6 22 38]
 [ 7 27 47]]
d^T * c^T:
[[ 4 12 20]
 [ 5 17 29]
 [ 6 22 38]
 [ 7 27 47]]
Are they equal? True


In [25]:
#Q10
matrix_x=np.array([[1, 2, 4], [3, 4, 6], [7, 8, 5], [9, 2, 1]])
matrix_x.reshape(6,2)

array([[1, 2],
       [4, 3],
       [4, 6],
       [7, 8],
       [5, 9],
       [2, 1]])