In [1]:
import numpy as np
import pandas as pd

In [6]:
# Compute the determinant of the following matrix.
firstMatrix = np.array([[1,3,2], [4,1,3], [2,5,2]])
print(np.linalg.det(firstMatrix))

16.999999999999993


In [11]:
# Eigenvalues and Eigenvectors
A = np.array([[4,2,3], [-1,1,-3], [2,4,9]])
eigenvalues = np.linalg.eig(A)[0]
eigenvectors = np.linalg.eig(A)[1]
print("Eigenvalues: {}".format(eigenvalues))
print("Eigenvectors: {}".format(eigenvectors))

Eigenvalues: [8. 3. 3.]
Eigenvectors: [[-0.40824829  0.0153225   0.9635814 ]
 [ 0.40824829 -0.83430241 -0.14040935]
 [-0.81649658  0.55109411 -0.22758756]]


In [13]:
# invers of matriks
B = np.array([[2,2,0], [0,0,1], [4,2,0]])
inversOfB = np.linalg.inv(B)
print("Invers of B: {}".format(inversOfB))

[[-0.5  0.   0.5]
 [ 1.   0.  -0.5]
 [ 0.   1.   0. ]]


In [16]:
# Verify B x B = Identity Matriks
multiplicateB = np.multiply(B,B)
print(multiplicateB)
print("The result is B X B is not identity matriks")

[[ 4  4  0]
 [ 0  0  1]
 [16  4  0]]
The result is B X B is not identity matriks


In [27]:
# Compute the matrix given by AB + 2A^2 - 3B
computeTheMatriks = (np.dot(A,B)) + (2 * np.dot(A,A)) - (np.dot(3,B))
print("The computation result on AB + 2A^2 - 3B is \n{}".format(computeTheMatriks))

The computation result on AB + 2A^2 - 3B is 
[[ 54  52  68]
 [-36 -34 -68]
 [ 72 104 154]]


In [30]:
# Find matriks Q and D such that A = QDQ^-1
D = np.diag(eigenvalues)
Q = eigenvectors
inversOfQ = np.linalg.inv(Q)
print("Matriks D: \n{}".format(D))
print("Matriks Q: \n{}".format(Q))
print("Matriks Q_invers: \n{}".format(inversOfQ))

Matriks D: 
[[8. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]
Matriks Q: 
[[-0.40824829  0.0153225   0.9635814 ]
 [ 0.40824829 -0.83430241 -0.14040935]
 [-0.81649658  0.55109411 -0.22758756]]
Matriks Q_invers: 
[[-0.48989795 -0.9797959  -1.46969385]
 [-0.38046442 -1.61250144 -0.61601851]
 [ 0.83628603 -0.38947664 -0.61288134]]


In [34]:
# Solved system of linear equations
one = np.array([[2,4,9], [4,3,8], [2,4,2]])
two = np.array([-18, -26, 17])
solvedResult = np.linalg.solve(one,two)
print("Result is: \n{}".format(solvedResult))

Result is: 
[-2.5  8.  -5. ]


In [53]:
# Find dimensions and transposes of matrices C and D
C = np.array([[0,1],[2,3],[4,5]]).reshape(3,2)
D = np.array([[0,1,2,3], [4,5,6,7]])
dimensionOfC = C.shape
dimensionOfD = D.shape
transposeOfC = C.T
transposeOfD = D.T
print("Dimension of C: {}".format(dimensionOfC))
print("Dimension of D: {}".format(dimensionOfD))
print("Transpose of C: \n{}".format(transposeOfC))
print("Transpose of D: \n{}".format(transposeOfD))

Dimension of C: (3, 2)
Dimension of D: (2, 4)
Transpose of C: 
[[0 2 4]
 [1 3 5]]
Transpose of D: 
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [52]:
# Verify that (CD)^T = D^T x C^T
CDT = np.dot(C,D).T
DTCT = np.dot(D.T, C.T)
print(np.allclose(CDT,DTCT))

True


In [55]:
# Reshape matriks into 6 x 2 matriks
theMatriks = np.array([[1,2,4],[3,4,6],[7,8,5],[9,2,1]])
reshapedMatriks = theMatriks.reshape(6,2)
print(reshapedMatriks)

[[1 2]
 [4 3]
 [4 6]
 [7 8]
 [5 9]
 [2 1]]
