#1

In [1]:
import numpy as np

# Define the matrix
matrix_A = np.array([[1, 3, 2],
                     [4, 1, 3],
                     [2, 5, 2]])

# Compute the determinant
determinant_A = np.linalg.det(matrix_A)

determinant_A

16.999999999999993

#2

In [2]:
matrix_A = np.array([[4, 2, 3],
                     [-1, 1, -3],
                     [2, 4, 9]])

eigenvalues, eigenvectors = np.linalg.eig(matrix_A)

print("Eigenvalues of matrix A:")
print(eigenvalues)

print("Eigenvectors of matrix A:")
print(eigenvectors)

Eigenvalues of matrix A:
[8. 3. 3.]
Eigenvectors of matrix A:
[[-0.40824829  0.0153225   0.9635814 ]
 [ 0.40824829 -0.83430241 -0.14040935]
 [-0.81649658  0.55109411 -0.22758756]]


#3

In [4]:
# Define matrix B
matrix_B = np.array([[2, 2, 0],
                     [0, 0, 1],
                     [4, 2, 0]])

# Compute the inverse
inverse_B = np.linalg.inv(matrix_B)

inverse_B

array([[-0.5,  0. ,  0.5],
       [ 1. ,  0. , -0.5],
       [ 0. ,  1. ,  0. ]])

#4

In [6]:
# Compute B x B
result = np.dot(matrix_B, matrix_B)

# Define the identity matrix
identity_matrix = np.eye(3)

# Check if B x B is equal to the identity matrix
is_identity = np.allclose(result, identity_matrix)

print("B x B is equal to the identity matrix:", is_identity)

B x B is equal to the identity matrix: False


#5

In [14]:
result_matrix = np.dot(matrix_A, matrix_B) + 2 * np.dot(matrix_A, matrix_A) - 3 * matrix_B

print("Result of matrix multiplication:")
print(result_matrix)

Result of matrix multiplication:
[[ 54  52  68]
 [-36 -34 -68]
 [ 72 104 154]]


#6

In [8]:
matrix_A = np.array([[4, 2, 3],
                     [-1, 1, -3],
                     [2, 4, 9]])

eigenvalues, eigenvectors = np.linalg.eig(matrix_A)

matrix_D = np.diag(eigenvalues)

Q_inv = np.linalg.inv(eigenvectors)

matrix_Q = eigenvectors
matrix_Q_inv = Q_inv

print("Matrix Q:")
print(matrix_Q)

print("Matrix D:")
print(matrix_D)

print("Matrix Q_inverse:")
print(matrix_Q_inv)

Matrix Q:
[[-0.40824829  0.0153225   0.9635814 ]
 [ 0.40824829 -0.83430241 -0.14040935]
 [-0.81649658  0.55109411 -0.22758756]]
Matrix D:
[[8. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]
Matrix Q_inverse:
[[-0.48989795 -0.9797959  -1.46969385]
 [-0.38046442 -1.61250144 -0.61601851]
 [ 0.83628603 -0.38947664 -0.61288134]]


#7

In [9]:
# Coefficients matrix
coefficients = np.array([[2, -4, 9],
                     [4, -3, 8],
                     [-2, 4, -2]])
# Constants matrix
constants = np.array([-38, -26,17])

# Solve the system of equations
solution = np.linalg.solve(coefficients, constants)

print("Solution to the system of equations:")
print(solution)

Solution to the system of equations:
[ 2.5  4.  -3. ]


#8

In [16]:
# Given matrices C and D
matrix_C = np.array([[0, 1],
                     [2, 3],
                     [4,5]])

matrix_D = np.array([[0, 1, 2, 3],
                     [4, 5, 6, 7]])

# Get the dimensions of matrices C and D
dimensions_C = matrix_C.shape
dimensions_D = matrix_D.shape

# Transpose matrices C and D
transpose_C = np.transpose(matrix_C)
transpose_D = np.transpose(matrix_D)

print("Dimensions of matrix C:", dimensions_C)
print("Dimensions of matrix D:", dimensions_D)

print("Transpose of matrix C:")
print(transpose_C)

print("Transpose of matrix D:")
print(transpose_D)

Dimensions of matrix C: (3, 2)
Dimensions of matrix D: (2, 4)
Transpose of matrix C:
[[0 2 4]
 [1 3 5]]
Transpose of matrix D:
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


#9

In [19]:
np.allclose(np.transpose(np.dot(matrix_C,matrix_D)),np.dot(np.transpose(matrix_D),np.transpose(matrix_C)))

True

#10

In [22]:
# Given matrix
matrix_to_reshape = np.array([[1, 2, 4],
                              [3, 4, 6],
                              [7, 8, 5],
                              [9, 2, 1]])

# Reshape the matrix into a 6 x 2 matrix
reshaped_matrix = np.reshape(matrix_to_reshape, (6, 2))
reshaped_matrix

array([[1, 2],
       [4, 3],
       [4, 6],
       [7, 8],
       [5, 9],
       [2, 1]])