In [1]:
import numpy as np

# Define the matrix as a 2D array
matrix = np.array([[1, 3, 2],
                   [4, 1, 3],
                   [2, 5, 2]])

# Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

print("Determinant of the matrix:")
print(determinant)


Determinant of the matrix:
16.999999999999993


In [2]:
import numpy as np

# Define the matrix A as a 2D array
A = np.array([[4, 2, 3],
              [-1, 1, -3],
              [2, 4, 9]])

# Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[8. 3. 3.]

Eigenvectors:
[[-0.40824829  0.0153225   0.9635814 ]
 [ 0.40824829 -0.83430241 -0.14040935]
 [-0.81649658  0.55109411 -0.22758756]]


In [3]:
import numpy as np

# Define the matrix B as a 2D array
B = np.array([[2, 2, 0],
              [0, 0, 1],
              [4, 2, 0]])

# Compute the inverse of matrix B
inverse_B = np.linalg.inv(B)

print("Inverse of matrix B:")
print(inverse_B)


Inverse of matrix B:
[[-0.5  0.   0.5]
 [ 1.   0.  -0.5]
 [ 0.   1.   0. ]]


In [4]:
import numpy as np

# Define the matrix B as a 2D array
B = np.array([[2, 2, 0],
              [0, 0, 1],
              [4, 2, 0]])

# Compute the product of B with itself
B_squared = np.dot(B, B)

# Define the identity matrix I as a 2D array
I = np.identity(3)

# Check if B_squared is equal to the identity matrix I
is_equal_to_I = np.array_equal(B_squared, I)

print("B x B:")
print(B_squared)

print("\nIs B x B equal to I?")
print(is_equal_to_I)


B x B:
[[4 4 2]
 [4 2 0]
 [8 8 2]]

Is B x B equal to I?
False


In [5]:
import numpy as np

# Define matrices A and B as 2D arrays
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Compute AB (matrix multiplication)
AB = np.dot(A, B)

# Compute A^2 (matrix multiplication of A with itself)
A_squared = np.dot(A, A)

# Compute the final result: AB + 2A^2 - 3B
result = AB + 2 * A_squared - 3 * B

print("Resulting matrix:")
print(result)


Resulting matrix:
[[18 24]
 [52 70]]


In [6]:
import numpy as np

# Given eigenvalues and eigenvectors
eigenvalues = np.array([7, 4, 3])
eigenvectors = np.array([[-0.33333333, -0.70710678, 0.1490712],
                         [0.66666667, 0.70710678, -0.74535599],
                         [0.66666667, 0, 0.64988827]])

# Form the diagonal matrix D using the eigenvalues
D = np.diag(eigenvalues)

# Form the matrix Q using the eigenvectors
Q = eigenvectors

# Compute the inverse of matrix Q
Q_inverse = np.linalg.inv(Q)

# Compute the final matrix A using A = QDQ^(-1)
A = np.dot(np.dot(Q, D), Q_inverse)

print("Matrix Q:")
print(Q)
print("\nMatrix D:")
print(D)
print("\nMatrix Q^(-1):")
print(Q_inverse)
print("\nMatrix A:")
print(A)


Matrix Q:
[[-0.33333333 -0.70710678  0.1490712 ]
 [ 0.66666667  0.70710678 -0.74535599]
 [ 0.66666667  0.          0.64988827]]

Matrix D:
[[7 0 0]
 [0 4 0]
 [0 0 3]]

Matrix Q^(-1):
[[ 1.05818692  1.05818692  0.97090653]
 [-2.14189252 -0.72767896 -0.34326729]
 [-1.08550651 -1.08550651  0.54275326]]

Matrix A:
[[ 3.10363085 -0.89636915 -1.0518154 ]
 [ 1.30728506  5.30728506  2.34635746]
 [ 2.82183179  2.82183179  5.58908408]]


In [10]:
import numpy as np

# Define the coefficient matrix A and the constant vector B
A = np.array([[2, -4, 9],
              [4, -3, 8],
              [-2, 4, -2]])

B = np.array([-38, -26, 17])

# Solve the system of equations using numpy's linalg.solve() function
solution = np.linalg.solve(A, B)

print("Solution (x, y, z):")
print(solution)


Solution (x, y, z):
[ 2.5  4.  -3. ]


In [11]:
import numpy as np

# Define matrix C as a 2D array
C = np.array([[0, 1],
              [2, 3],
              [4, 5]])

# Define matrix D as a 2D array
D = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])

# Get the dimensions of matrix C and D
dimensions_C = C.shape
dimensions_D = D.shape

# Get the transpose of matrix C and D
transpose_C = np.transpose(C)
transpose_D = np.transpose(D)

print("Dimensions of matrix C:", dimensions_C)
print("Transpose of matrix C:")
print(transpose_C)

print("\nDimensions of matrix D:", dimensions_D)
print("Transpose of matrix D:")
print(transpose_D)


Dimensions of matrix C: (3, 2)
Transpose of matrix C:
[[0 2 4]
 [1 3 5]]

Dimensions of matrix D: (2, 4)
Transpose of matrix D:
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [12]:
import numpy as np

# Define matrix C and D as 2D arrays
C = np.array([[0, 1],
              [2, 3],
              [4, 5]])

D = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])

# Compute the product of CD
CD = np.dot(C, D)

# Compute the transpose of CD
transpose_CD = np.transpose(CD)

# Compute the transpose of D and C
transpose_D = np.transpose(D)
transpose_C = np.transpose(C)

# Compute the product of D^T and C^T
product_DTC = np.dot(transpose_D, transpose_C)

# Verify if (CD)^T is equal to D^T * C^T
is_equal = np.array_equal(transpose_CD, product_DTC)

print("Transpose of (CD):")
print(transpose_CD)

print("\nProduct of D^T * C^T:")
print(product_DTC)

print("\nIs (CD)^T equal to D^T * C^T?")
print(is_equal)


Transpose of (CD):
[[ 4 12 20]
 [ 5 17 29]
 [ 6 22 38]
 [ 7 27 47]]

Product of D^T * C^T:
[[ 4 12 20]
 [ 5 17 29]
 [ 6 22 38]
 [ 7 27 47]]

Is (CD)^T equal to D^T * C^T?
True


In [15]:
import numpy as np

# Given matrix
matrix = np.array([[1, 2, 4],
                   [3, 4, 6],
                   [7, 8, 5],
                   [9, 2, 1]])

# Reshape the matrix to a 6x2 matrix
reshaped_matrix = matrix.reshape(6, 2)

print("Original matrix:")
print(matrix)
print("\nReshaped 6x2 matrix:")
print(reshaped_matrix)


Original matrix:
[[1 2 4]
 [3 4 6]
 [7 8 5]
 [9 2 1]]

Reshaped 6x2 matrix:
[[1 2]
 [4 3]
 [4 6]
 [7 8]
 [5 9]
 [2 1]]
